# Generated by Django 5.2.5 on 2025-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('id_rol_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mantenimiento_usuarios',
                'managed': False,
            },
        ),
    ]
