# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos_Inventario_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_movimiento_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_movimiento_inventario')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes')),
                ('id_tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipo_movimiento_inventario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario de Sucursal',
                'verbose_name_plural': 'Movimientos de Inventario de Sucursal',
            },
        ),
    ]
