# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios_Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('nombre_reporte', models.CharField(blank=True, max_length=255, null=True)),
                ('id_estado_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_envio_receta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Envío de Receta',
                'verbose_name_plural': 'Envío de Recetas',
            },
        ),
        migrations.CreateModel(
            name='Recetas_Medicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('referencia_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('referente_receta', models.CharField(blank=True, max_length=255, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('id_usuario_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Envio_Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.envios_recetas')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.recetas_medicas')),
            ],
            options={
                'verbose_name': 'Detalle de Envío de Recetas',
                'verbose_name_plural': 'Detalles de Envío de Recetas',
            },
        ),
    ]
