# Generated by Django 5.2.5 on 2025-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Reporte_Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reportada', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Reporte de Vencimiento',
                'verbose_name_plural': 'Detalles de Reporte de Vencimiento',
            },
        ),
        migrations.CreateModel(
            name='Reportes_Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reporte de Vencimiento',
                'verbose_name_plural': 'Reportes de Vencimiento',
            },
        ),
    ]
