# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_alerta')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes')),
                ('id_tipo_alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipo_alerta')),
                ('id_usuario_atendio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Reportes_Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.CharField(max_length=255)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_vencimiento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Reporte de Vencimiento',
                'verbose_name_plural': 'Reportes de Vencimiento',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Reporte_Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reportada', models.IntegerField()),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes')),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas_vencimientos.reportes_vencimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Reporte de Vencimiento',
                'verbose_name_plural': 'Detalles de Reporte de Vencimiento',
            },
        ),
    ]
