# Generated by Django 5.2.5 on 2025-09-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_vencimientos', '0001_initial'),
        ('mnt_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas_inventario',
            name='id_usuario_atendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mnt_usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='reportes_vencimiento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnt_usuarios.usuario'),
        ),
    ]
