# Generated by Django 5.2.5 on 2025-09-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas_vencimientos', '0001_initial'),
        ('inventario', '0002_initial'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas_inventario',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_alerta'),
        ),
        migrations.AddField(
            model_name='alertas_inventario',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes'),
        ),
        migrations.AddField(
            model_name='alertas_inventario',
            name='id_tipo_alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipo_alerta'),
        ),
    ]
