# Generated by Django 5.2.5 on 2025-09-22 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas_vencimientos', '0002_initial'),
        ('inventario', '0002_initial'),
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas_inventario',
            name='id_usuario_atendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_reporte_vencimiento',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes'),
        ),
        migrations.AddField(
            model_name='reportes_vencimiento',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_vencimiento'),
        ),
        migrations.AddField(
            model_name='reportes_vencimiento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_reporte_vencimiento',
            name='id_reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas_vencimientos.reportes_vencimiento'),
        ),
    ]
