# Generated by Django 5.2.5 on 2025-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_disponible', models.IntegerField()),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('requiere_receta', models.BooleanField(blank=True, null=True)),
                ('es_controlado', models.BooleanField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
