# Generated by Django 5.2.5 on 2025-09-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('requiere_receta', models.BooleanField(blank=True, null=True)),
                ('es_controlado', models.BooleanField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, default=0, null=True)),
                ('id_condicion_almacenamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.condiciones_almacenamiento')),
                ('id_estado_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_producto')),
                ('id_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.laboratorios')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.presentaciones')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.unidades_medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_disponible', models.IntegerField()),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_estado_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_lote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
