# Generated by Django 5.2.5 on 2025-09-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='id_estado_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_lote'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_condicion_almacenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.condiciones_almacenamiento'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_estado_producto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.laboratorio'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.presentaciones'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.unidades_medida'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos'),
        ),
    ]
