# Generated by Django 5.2.5 on 2025-09-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lotes',
            constraint=models.UniqueConstraint(fields=('id_producto', 'numero_lote'), name='uq_lotes_producto_numero'),
        ),
    ]
