# Generated by Django 5.2.5 on 2025-09-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepciones_Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('numero_envio_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estado_recepcion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Recepción de Envío',
                'verbose_name_plural': 'Recepciones de Envío',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes')),
                ('id_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_almacenamiento.recepciones_envio')),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
            },
        ),
    ]
