# Generated by Django 5.2.5 on 2025-09-16 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_almacenamiento', '0002_alter_recepciones_envio_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciones_envio',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recepciones_envio',
            name='fecha_recepcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
