# Generated by Django 5.2.5 on 2025-09-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_almacenamiento', '0003_recepciones_envio_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepciones_envio',
            name='comentario',
        ),
    ]
