# Generated by Django 5.2.5 on 2025-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.IntegerField()),
                ('cantidad_contada', models.IntegerField()),
                ('diferencia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
            },
        ),
        migrations.CreateModel(
            name='Inventario_Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Inventario Físico',
                'verbose_name_plural': 'Inventarios Físicos',
            },
        ),
    ]
