# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Inventario Físico',
                'verbose_name_plural': 'Inventarios Físicos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.IntegerField()),
                ('cantidad_contada', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes')),
                ('id_conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajustes_inventario.inventario_fisico')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
            },
        ),
    ]
