# Generated by Django 5.2.5 on 2025-09-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_inventario', '0001_initial'),
        ('mnt_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnt_usuarios.usuario'),
        ),
    ]
