# Generated by Django 5.2.5 on 2025-09-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes_inventario', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_conteo',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lotes'),
        ),
    ]
