# Generated by Django 5.2.5 on 2025-09-22 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes_inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_fisico',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_conteo',
            name='id_conteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajustes_inventario.inventario_fisico'),
        ),
    ]
