# Generated by Django 5.2.5 on 2025-10-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_inventario', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_fisico',
            name='tipo_ajuste',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], default='Ingreso', max_length=20),
        ),
    ]
