# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_Faltantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('id_estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.estado_solicitud')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.usuarios')),
            ],
            options={
                'verbose_name': 'Solicitud de Faltantes',
                'verbose_name_plural': 'Solicitudes de Faltantes',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Solicitud_Faltantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('es_urgente', models.BooleanField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes_bodega_central.solicitudes_faltantes')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Faltantes',
                'verbose_name_plural': 'Detalles de Solicitud de Faltantes',
            },
        ),
    ]
