# Generated by Django 5.2.5 on 2025-10-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_vencimientos', '0004_delete_alertas_inventario'),
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_Alerta',
        ),
        migrations.DeleteModel(
            name='Tipo_Alerta',
        ),
    ]
