# Generated by Django 5.2.5 on 2025-09-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_usuarios_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_rol',
        ),
    ]
