# Generated by Django 5.2.5 on 2025-09-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_inventario', '0002_alter_inventario_fisico_id_usuario'),
        ('alertas_vencimientos', '0002_alter_alertas_inventario_id_usuario_atendio_and_more'),
        ('mantenimiento', '0004_remove_usuarios_id_rol'),
        ('mnt_usuarios', '0001_initial'),
        ('recepcion_almacenamiento', '0002_alter_recepciones_envio_id_usuario'),
        ('recetas', '0002_alter_envios_recetas_id_usuario_and_more'),
        ('salidas_devoluciones', '0002_alter_movimientos_inventario_sucursal_id_usuario'),
        ('solicitudes_bodega_central', '0002_alter_solicitudes_faltantes_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnt_usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
